//! Bidirectional synchronization with loop prevention (M12).
//!
//! [`sync`] mirrors internal commits onto a public repository (forward) and
//! then walks the public history back, recognizing commits RepoSync itself
//! generated (via the [`reposync_git::GENERATED_TRAILER`] marker) so they are
//! never re-imported — that is what stops sync loops. Public-side changes that
//! were *not* generated by RepoSync are external edits and are handled according
//! to the configured [`SyncStrategy`].

use reposync_core::CommitId;
use reposync_git::{generated_source, CommitSpec, GitRepo};
use reposync_state::State;
use reposync_transform::Transformation;

use crate::history::replay_history;
use crate::Error;

/// Strategy for handling changes that appear only on the public (mirror) side
/// and were not generated by RepoSync.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum SyncStrategy {
    /// External public changes are conflicts; the sync fails with a report.
    Fail,
    /// External public changes are imported as new internal commits.
    Import,
}

/// A change found on the public side that was not produced by RepoSync.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Conflict {
    /// The public commit id that triggered the conflict.
    pub public_commit: CommitId,
    /// The commit message, for reporting.
    pub message: String,
}

/// Outcome of a bidirectional sync.
#[derive(Debug, Clone, PartialEq, Eq, Default)]
pub struct SyncReport {
    /// Internal commits replayed to the public side.
    pub forward_replayed: usize,
    /// Public commits recognized as generated mirrors (skipped on reverse).
    pub skipped_generated: usize,
    /// External public commits imported as new internal commits.
    pub imported: usize,
    /// External public commits that conflicted (with [`SyncStrategy::Fail`]).
    pub conflicts: Vec<Conflict>,
}

/// Two-way sync between `internal` (source of truth) and `public` (mirror).
///
/// 1. **Forward**: replay unmapped internal commits onto `public`, marking each
///    as generated (so it is recognizable on the reverse pass) and recording the
///    source→destination mapping.
/// 2. **Reverse**: walk `public` history. Commits carrying the generated marker
///    are our own mirrored output and are skipped (loop prevention). Commits
///    without the marker are external changes, handled per `strategy`.
///
/// # Errors
///
/// Returns the first git/state/transform error, or [`Error::Conflict`] if
/// external changes were found and `strategy` is [`SyncStrategy::Fail`].
pub fn sync(
    internal: &GitRepo,
    public: &GitRepo,
    transforms: &[&dyn Transformation],
    state: &State,
    strategy: SyncStrategy,
) -> Result<SyncReport, Error> {
    let mut report = SyncReport::default();

    // --- Forward: internal -> public (marks + records via replay). ---
    let forward = replay_history(internal, public, transforms, Some(state), None, None)?;
    report.forward_replayed = forward.commits_replayed;

    // --- Reverse: public -> internal, loop prevention via markers. ---
    let public_history = public.history(None)?; // newest-first
    let ordered: Vec<CommitId> = public_history.into_iter().rev().collect(); // oldest-first
    for pid in ordered {
        let info = public.commit_info(&pid)?;
        if generated_source(&info.message).is_some() {
            // Our own mirrored output. Skip it; even if the source commit has
            // since vanished it cannot form a loop, so we just drop it.
            report.skipped_generated += 1;
            continue;
        }

        // External (non-generated) change on the public side.
        match strategy {
            SyncStrategy::Fail => {
                report.conflicts.push(Conflict {
                    public_commit: pid.clone(),
                    message: info.message.clone(),
                });
            }
            SyncStrategy::Import => {
                let snapshot = public.snapshot_at_ref(pid.as_str())?;
                let spec = CommitSpec {
                    message: info.message.clone(),
                    author: Some(info.author.clone()),
                    committer: Some(info.committer.clone()),
                };
                let new_id = internal.write_commit(&snapshot, &spec)?;
                state.record(&pid, &new_id)?;
                report.imported += 1;
            }
        }
    }

    if !report.conflicts.is_empty() {
        return Err(Error::Conflict(report));
    }
    Ok(report)
}

#[cfg(test)]
mod tests {
    use super::*;
    use reposync_core::{Blob, FileEntry, RepoPath, RepositorySnapshot, Signature};
    use reposync_transform::{Filter, Transformation};

    fn commit(repo: &GitRepo, files: &[(&str, &[u8])], author: &str) {
        repo.set_identity("ignored", "ignored@example.com").unwrap();
        let mut snapshot = RepositorySnapshot::new();
        for (path, content) in files {
            snapshot.insert(FileEntry::regular(
                RepoPath::new(*path).unwrap(),
                Blob::from_bytes(*content),
            ));
        }
        let signature = Signature::new(author, format!("{author}@example.com"), 1_700_000_000, 0);
        let spec = CommitSpec {
            message: format!("commit by {author}"),
            author: Some(signature.clone()),
            committer: Some(signature),
        };
        repo.write_commit(&snapshot, &spec).unwrap();
    }

    #[test]
    fn recognizes_generated_commits_and_avoids_loops() {
        let root = tempfile::TempDir::new().unwrap();
        let internal = GitRepo::init(root.path().join("internal")).unwrap();
        let public = GitRepo::init(root.path().join("public")).unwrap();
        let state = State::open(&root.path().join("state.db")).unwrap();

        commit(&internal, &[("a.txt", b"a")], "Alice");
        commit(&internal, &[("a.txt", b"a"), ("b.txt", b"b")], "Bob");

        let filter: Vec<Box<dyn Transformation>> = vec![Box::new(Filter::new(["**"]))];
        let t: Vec<&dyn Transformation> = filter.iter().map(|b| &**b).collect();

        let first = sync(&internal, &public, &t, &state, SyncStrategy::Fail).unwrap();
        assert_eq!(first.forward_replayed, 2);
        assert_eq!(first.skipped_generated, 2);
        assert!(first.conflicts.is_empty());

        // A second sync must not duplicate or loop: internal/public unchanged.
        let second = sync(&internal, &public, &t, &state, SyncStrategy::Fail).unwrap();
        assert_eq!(second.forward_replayed, 0);
        assert_eq!(second.skipped_generated, 2);
        assert!(second.conflicts.is_empty());

        assert_eq!(internal.history(None).unwrap().len(), 2);
        assert_eq!(public.history(None).unwrap().len(), 2);
        assert_eq!(state.mappings().unwrap().len(), 2);
    }

    #[test]
    fn external_change_is_a_conflict_under_fail_strategy() {
        let root = tempfile::TempDir::new().unwrap();
        let internal = GitRepo::init(root.path().join("internal")).unwrap();
        let public = GitRepo::init(root.path().join("public")).unwrap();
        let state = State::open(&root.path().join("state.db")).unwrap();

        commit(&internal, &[("a.txt", b"a")], "Alice");
        let filter: Vec<Box<dyn Transformation>> = vec![Box::new(Filter::new(["**"]))];
        let t: Vec<&dyn Transformation> = filter.iter().map(|b| &**b).collect();
        sync(&internal, &public, &t, &state, SyncStrategy::Fail).unwrap();

        // A human edit lands on the public side (no generated marker).
        commit(&public, &[("a.txt", b"a"), ("human.txt", b"edit")], "Mallory");

        let result = sync(&internal, &public, &t, &state, SyncStrategy::Fail);
        let err = result.expect_err("expected a conflict");
        let Error::Conflict(report) = err else {
            panic!("expected Error::Conflict, got {err:?}");
        };
        assert_eq!(report.conflicts.len(), 1);
        assert_eq!(report.skipped_generated, 1);
    }

    #[test]
    fn import_strategy_brings_external_changes_in() {
        let root = tempfile::TempDir::new().unwrap();
        let internal = GitRepo::init(root.path().join("internal")).unwrap();
        let public = GitRepo::init(root.path().join("public")).unwrap();
        let state = State::open(&root.path().join("state.db")).unwrap();

        commit(&internal, &[("a.txt", b"a")], "Alice");
        let filter: Vec<Box<dyn Transformation>> = vec![Box::new(Filter::new(["**"]))];
        let t: Vec<&dyn Transformation> = filter.iter().map(|b| &**b).collect();
        sync(&internal, &public, &t, &state, SyncStrategy::Fail).unwrap();

        commit(&public, &[("a.txt", b"a"), ("human.txt", b"edit")], "Mallory");

        let report = sync(&internal, &public, &t, &state, SyncStrategy::Import).unwrap();
        assert_eq!(report.imported, 1);
        assert_eq!(internal.history(None).unwrap().len(), 2);
    }
}

